name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: bundle exec rspec
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          username: "210731252211"
          key: "bdcf10b94c24b71b5c0cfd2f3ee670a83ec3437b92c77e511dee19f651d261e5"
          script: |
            cd /var/www/testable1
            git pull origin main
            bundle install --deployment --without development test
            bundle exec rake db:migrate
            sudo systemctl restart app
