name: Deploy app

on:
  push:
    branches: [ main ]

jobs:
  #First we will see the application build or not , then we will deploy in EC2

  Deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy in EC2
        run: |
          cd /var/www/testable1
          export RAILS_ENV=production
          git pull origin main
          bundle install
          bundle exec rails db:migrate
          killall -9 ruby
          puma -d
          sudo service nginx restart