name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --deployment --without development test

        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

      - name: Deploy code
        run: |
          
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key &&
          ssh -i private_key ${USER_NAME}@${HOSTNAME} "cd /home/ubuntu/var/www/testable1 && git pull && bundle install --jobs 4 --retry 3 --deployment --without development test && bundle exec rake assets:precompile RAILS_ENV=production && sudo systemctl restart"
